#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find . -name install.sh -print0 | while IFS= read -r -d '' installer ; do "$installer" ; done
